### ISSUE TITLE
Update CI/CD

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/vanillaes#14]
Update CI/CD

Changes:

- run 'verify' on pull requests
- update actions
- test on both node v14 and v16

Note: Unscoped packages don't get deployed to GH Packages

## Checklist

- [x] absurdum
- [x] computer-science
- [x] csv
- [x] esmtk
- [x] frontmeta
- [x] interpolate
- [x] jqkill
- [x] mock-console
- [x] monaco-editor-es
- [x] tape-es

## Notes

*latest.yml*
```yaml
name: Latest

on: 
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install
        run: npm i
      - name: Test
        run: npm t --if-present
      - name: Lint
        run: npm run lint --if-present
      - name: Types
        run: npm run types --if-present

```

*release.yml*
```yaml
name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Verify
        run: |
          npm i
          npm run preversion
  npm:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
        npm publish --access public
  gh:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
        ORG="$(echo '${{ github.repository }}' | cut -d'/' -f1)"
        echo "registry=https://npm.pkg.github.com/$ORG" > .npmrc
        npm publish

```
