### ISSUE TITLE
Republish All Projects Under the @Vanillaes Org

### ISSUE THREAD

**Issue by evanplaice** [vanillaes/vanillaes#7]
Move all the packages in this org under the @vanillaes scope and dual-publish GH Packages.

## Checklist

- [x] absurdum 
- [x] computer-science
- [x] csv-es
- [x] frontmeta
- [x] interpolate-es
- [x] jqkill
- [x] markdown-es
- [x] mock-console-es
- [x] tape-es
- [x] ujpm

## Notes

Tasks:
- update pkg.name
- fix broken references
- remove package-lock.json
- update CI/CD
- update badges
- update instructions
- update CHANGELOG.md

*latest.yml*
```yaml
name: Latest

on: [push]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install
        run: npm i
      - name: Test
        run: npm t
      - name: Lint
        run: npm run lint
      - name: Types
        run: npm run types
```

*release.yml*
```yaml

name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Verify
        run: |
          npm ci
          npm run preversion
  npm:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Publish
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
        npm publish --access public
  gh:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Publish
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
        ORG="$(echo '${{ github.repository }}' | cut -d'/' -f1)"
        echo "registry=https://npm.pkg.github.com/$ORG" > .npmrc
        npm publish
```
